### Create Product
POST http://localhost:9000/products
Content-Type: application/json

{
    "name": "Mac Pro",
    "description": "A Desktop Computer",
    "stock": 200,
    "price": 9000
}

### Get Products
GET http://localhost:9000/products
Content-Type: application/json

### Update Stock
PATCH http://localhost:9000/products/3
Content-Type: application/json

    {
    "stock":50
    }
